### ISSUE TITLE
Users should be able to opt out of the return tile animation. 

### ISSUE THREAD

**Issue by akshar07** [sandstreamdev/react-swipeable-list#141]
When deleting something from a list, the return animation of the tile makes it confusing for the user. 

the current animations are perfect for functionality like mark as unread but for delete or remove functionality, the tile should not perform the return animation.

**Comment by marekrozmus** [comment]
Hi, thanks for feature request :) I'm currently fixing somehow related issue #133. You can check propsal of solution here #144. Your issue fix proposal is here: https://github.com/sandstreamdev/react-swipeable-list/blob/fda08471d2d3cc42be63a0cb689da26957831fc5/examples/src/App.js#L38
There will be possibility to have: default return animation, remove animation or disable animation (item will stay where it was moved). This is just draft so all comments are welcome.

**Comment by marekrozmus** [comment]
@all-contributors please add @akshar07 for ideas

**Comment by marekrozmus** [comment]
@akshar07 [release with fixes](https://github.com/sandstreamdev/react-swipeable-list/releases/tag/v0.5.0) is ready - enjoy 🎉
