### ISSUE TITLE
unable to style ListItem component

### ISSUE THREAD

**Issue by davidreact** [sandstreamdev/react-swipeable-list#159]
I have an webpage where the background is a gradient. I can't seem to be able to remove the white background and the flex properties from the listitem wrapper without having to built the css file from scratch. Not sure if I'm doing something wrong.

.content {
  width: 100%;
  align-items: center;
  box-sizing: border-box;
  background-color: #fff;
  height: 100%;
  display: flex;
}

Screenshot of issue
https://prnt.sc/seic00

**Comment by marekrozmus** [comment]
Hi. 

Unfortunately it looks like you can't do this with current implementation (at least to make it work between versions). For dev purposes you could override the generated class name `SwipeableListItem_content_3wMba` but when new version will be released this will change as you know.

I would need to implement passing some additional styles from outside the component.

What exact styles you would like to have besides transparent background?
Could you please provide screenshot of what you want to achieve? I just wonder what changes I would need to implement (only `content` div styling or some other elements of `SwipeableListItem`). And it would be easier to test the solution you need 🙂

**Comment by davidreact** [comment]
only need to remove background color and display: flex from content. These properties can be set at the item level with a div.

.content {
width: 100%;
align-items: center;
box-sizing: border-box;
height: 100%;
}

**Comment by marekrozmus** [comment]
Ok, great, so please usa that temporary hack for now. I'll fix that issue as soon as I have some free time.

**Comment by marekrozmus** [comment]
@all-contributors please add @davidreact for ideas
