### ISSUE TITLE
React 18: Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<SwipeableListItem> & Readonly<ISwipeableListItemProps>'

### ISSUE THREAD

**Issue by cakirpro** [sandstreamdev/react-swipeable-list#229]
After upgrading to React 18, this error occurs where compiler complains about missing children property in ISwipeableListItemProps.

The error could be eliminated by adding the children property to ISwipeableListItemProps.

`children?: React.ReactNode | undefined;`

A fix would be appreciated. Thanks!

**Comment by jakubbogacz** [comment]
Hi @cakirpro, we have just published new package version. Can you confirm if it closes the issue?
