### ISSUE TITLE
"Module not found: Can't resolve '@sandstreamdev/react-swipeable-list'"

### ISSUE THREAD

**Issue by wildeyes** [sandstreamdev/react-swipeable-list#42]
**Describe the bug**
Doesn't work with typescript + create-react-app from the box.

**To Reproduce**
1. `npx create-react-app app --typescript`.
2. try to import this module.
3. get error from either typescript or webpack (couldn't tell): Module not found: Can't resolve '@sandstreamdev/react-swipeable-list'

**Expected behavior**

**Screenshots**
https://codesandbox.io/s/sandstreamdevreact-swipeable-list-with-typescript-9fgmv

**notes**:
`import '@sandstreamdev/react-swipeable-list/dist/styles.css'` does actually work, so I'm convinced it's something to do with tsconfig's `compilerOptions.module: esnext` which can't be overridden, so we must think of some workaround.

**Comment by marekrozmus** [comment]
@wildeyes Thank you for your report. Unfortunately we are very busy at the moment. Will take a look at it as soon as possible. Feel free to submit a PR for this if you can.

**Comment by wildeyes** [comment]
👌

**Comment by marekrozmus** [comment]
@all-contributors please add @wildeyes for bug

**Comment by marekrozmus** [comment]
@wildeyes Let me know if the current version work ok, if not then please reopen or created new issue with some additional details.

**Comment by dhruvjain501git** [comment]
getting same issue a above , please can any one help

**Comment by dhruvjain501git** [comment]
Module not found: Can't resolve '@sandstreamdev/react-swipeable-list' in '/Users/dhruv.jain/Documents/Projects/Aplio/MLB_React4/src/mlb-screens/Routines'
