### ISSUE TITLE
Swiping doesn't work in Safari on Mac

### ISSUE THREAD

**Issue by derUli** [sandstreamdev/react-swipeable-list#72]
**Describe the bug**
The swiping doesn't work in Safari on Mac.

**Steps To Reproduce**
1. Open the demo page in Safari on Mac.
2. Try to swipe something

**Expected behavior**
It should be swipable as shown in this gif https://raw.githubusercontent.com/sandstreamdev/react-swipeable-list/master/docs/example.gif

**Actual behavior**
It selects text

**Desktop (please complete the following information):**
 - macOS Mojave
 - Safari
 - 13.0.4 (14608.4.9.1.4)

**Additional Information**
Mobile Safari and other browsers works.

**Comment by marekrozmus** [comment]
@all-contributors please add @derUli for bug
