### ISSUE TITLE
Slow scrolling

### ISSUE THREAD

**Issue by Iliyaz1995** [sandstreamdev/react-swipeable-list#90]
Everything works like a charm but when you scroll the list in a mobile device it feels a lot slower than the native scrolling. Can you please look into that.

**Comment by marekrozmus** [comment]
@Iliyaz1995 Thank you for the report 🙂 

Please check if this is works for you:
`npm install git://github.com/sandstreamdev/react-swipeable-list.git#fix_for_issue_90`

If yes then I'll add it in next release which should be ready next week.

**Comment by marekrozmus** [comment]
@all-contributors please add @Iliyaz1995 for bug
